---
services:
  nginx-autoindex:
    container_name: nginx-autoindex
    build:
      context: .
      dockerfile: Dockerfile
    image: dceoy/nginx-autoindex:latest
    network_mode: bridge
    ports:
      - 80:80
    volumes:
      - ${PWD}:/var/lib/nginx/html:ro
    entrypoint:
      - /usr/sbin/nginx
    command:
      - -g
      - daemon off;
