---
name: CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:
    inputs:
      workflow:
        required: true
        type: choice
        options:
          - lint-and-scan
          - build
        description: Choose the workflow to run
        default: lint-and-scan
jobs:
  docker-lint-and-scan:
    if: >
      github.event_name == 'push'
      || github.event_name == 'pull_request'
      || (github.event_name == 'workflow_dispatch' && inputs.workflow == 'lint-and-scan')
    uses: dceoy/gh-actions-for-devops/.github/workflows/docker-lint-and-scan.yml@main
  docker-build-and-push:
    if: >
      github.event_name == 'push'
      || (
        github.event_name == 'workflow_dispatch'
        && inputs.workflow == 'build'
        && (! (failure() || cancelled()))
      )
    needs:
      - docker-lint-and-scan
    uses: dceoy/gh-actions-for-devops/.github/workflows/docker-build-and-push.yml@main
    with:
      registry: docker.io
      registry-user: ${{ github.repository_owner }}
      image-name: ${{ github.repository_owner }}/nginx-autoindex
      context: .
      file: ./Dockerfile
      platforms: linux/amd64,linux/arm64
      push: true
      scan-before-build: false
      scan-after-build: true
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  dependabot-auto-merge:
    if: >
      github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    needs:
      - docker-lint-and-scan
    uses: dceoy/gh-actions-for-devops/.github/workflows/dependabot-auto-merge.yml@main
    with:
      unconditional: true
